from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel
from typing import Optional

app = FastAPI(
    title="Task API",
    version="1.0",
    description="A simple CRUD API for managing tasks"
)

tasks = [
    {"id": 1, "title": "Finish CRUD project", "done": False},
    {"id": 2, "title": "Play the piano", "done": True},
    {"id": 3, "title": "Go for a walk", "done": False},
]


class CreateTask(BaseModel):
    """Model for creating a new task."""
    title: Optional[str] = None

class UpdateTask(BaseModel):
    """Model for updating an existing task."""
    title: Optional[str] = None
    done: Optional[bool] = None


@app.get("/")
def read_root():
    """
    Root endpoint, provides API info.

    Returns:
        JSON with the API name, version, and available endpoints.
    """
    return {
        "name": "Task API",
        "version": "1.0",
        "endpoints": ["/tasks"]
    }

@app.get("/health")
def health_check():
    """
    Health check endpoint.

    Returns:
        {"status": "ok"}.
    """
    return {"status": "ok"}

@app.get("/tasks")
def get_tasks():
    """
    Retrieve all tasks.

    Returns:
        A list of all availlable tasks.
    """
    return tasks

@app.get("/tasks/{task_id}")
def get_task(task_id: int):
    """
    Get a single task by its ID.

    Args:
        task_id: The unique task ID.

    Returns:
        The task object, or a 404 error if not found.
    """
    for task in tasks:
        if task["id"] == task_id:
            return task
    return JSONResponse(
        status_code=404,
        content={"error": f"Task {task_id} not found"}
    )

@app.post("/tasks", status_code=201)
def add_task(task_data: CreateTask):
    """
    Create a new task.

    Args:
        task_data: JSON object with a 'title' field (required).

    Returns:
        The newly created task with an autogenerated ID and `done: false`.
    """
    if task_data.title is None or not task_data.title.strip():
        return JSONResponse(
            status_code=400,
            content={"error": "The title is required and can't be empty"}
        )

    post_id = tasks[-1]["id"] + 1 if tasks else 1
    new_task = {
        "id": post_id,
        "title": task_data.title.strip(),
        "done": False
    }
    tasks.append(new_task)
    return new_task

@app.put("/tasks/{task_id}")
def update_task(task_id: int, update: UpdateTask):
    """
    Update an existing task.

    You can update the title, the done status, or both.

    Args:
        task_id: The ID of the task to update.
        update: JSON with optional 'title' and/or 'done' fields.

    Returns:
        The updated task, or 404 if not found, or 400 if title is empty.
    """
    task = None
    for tsk in tasks:
        if tsk["id"] == task_id:
            task = tsk
            break

    if task is None:
        return JSONResponse(
            status_code=404,
            content={"error": f"Task {task_id} not found"}
        )

    if update.title is not None and not update.title.strip():
        return JSONResponse(
            status_code=400,
            content={"error": "Title cannot be empty"}
        )

    if update.title is not None:
        task["title"] = update.title.strip()
    if update.done is not None:
        task["done"] = update.done

    return task

@app.delete("/tasks/{task_id}", status_code=204)
def delete_task(task_id: int):
    """
    Delete a task by its ID.

    Args:
        task_id: The ID of the task to remove.

    Returns:
        204 No Content on success, or 404 with error.
    """
    task_idx = None
    for idx, t in enumerate(tasks):
        if t["id"] == task_id:
            task_idx = idx
            break

    if task_idx is None:
        return JSONResponse(
            status_code=404,
            content={"error": f"Task {task_id} not found"}
        )

    tasks.pop(task_idx)
    return None 
